name: depi
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.6.4
  - libffi=3.4.4
  - openssl=3.0.16
  - pip=25.0
  - python=3.12.9
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - anyio==4.9.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - colorama==0.4.6
      - fastapi==0.115.12
      - flatbuffers==25.2.10
      - fonttools==4.57.0
      - h11==0.14.0
      - idna==3.10
      - imbalanced-learn==0.13.0
      - imblearn==0.0
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - matplotlib==3.10.1
      - mlflow==2.21.3
      - mlflow-skinny==2.21.3
      - namex==0.0.8
      - numpy==2.0.2
      - opt-einsum==3.4.0
      - optree==0.15.0
      - pandas==2.2.3
      - pillow==11.1.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - requests==2.32.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - six==1.17.0
      - sklearn-compat==0.1.3
      - sniffio==1.3.1
      - sqlparse==0.5.3
      - starlette==0.46.1
      - tensorboard-data-server==0.7.2
      - termcolor==3.0.1
      - threadpoolctl==3.6.0
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==2.4.0
      - uvicorn==0.34.0
      - waitress==3.0.2
      - wrapt==1.17.2
      - xgboost==3.0.0
      - zipp==3.21.0
